# -*- coding: utf-8 -*-
"""10Data Visualization3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kylDH1v_BM_YeS2CMldmb6igGWStLkXm
"""

import numpy as np
import pandas as pd

df = pd.read_csv("data10.csv")
df.columns = ["col1","col2","col3","col4","col5"] #change the column names

df.head() #displays first 5 rows of dataset

column = len(list(df)) # list()-converts the column length and then len()-will count the total number of columns
column

"""1.List down the features and their types (e.g., numeric, nominal) available in the dataset."""

df.info() #display the col names, datatype, null values, row count

"""Hence the dataset contains 4 numerical columns and 1 object column"""

np.unique(df["col5"]) # finds all unique values in col5

df.describe() # calculates the statistics for numeric columns which includes mean, count, std, min, max, 25% Q1, 75% Q2 etc

"""Compute and display summary statistics for each feature available in the dataset."""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns # imports seaborn used for advanced visualizations
import matplotlib
import matplotlib.pyplot as plt #importing the plotting module
# %matplotlib inline

"""Data Visualization-Create a histogram for each feature in the dataset to illustrate the feature distributions. Plot each histogram."""

fig, axes = plt.subplots(2, 2, figsize=(16, 8))
"""
subplots-> creates a multiple graphs inside one figure
2,2 creates 2rows, 2column mean total 4 graph spaces as
axes[0,0]   axes[0,1]

axes[1,0]   axes[1,1]
figsize=(16,8) sets graph size
"""
"""
what is histogram explain in simple words

A histogram is a graph used to show how data is distributed.

It groups numbers into ranges (called bins) and shows how many values fall in each range.
"""

axes[0,0].set_title("Distribution of First Column") #sets title for first graph
axes[0,0].hist(df["col1"]); #creates histogram for column1
"""
axes[0,0]
row 0
column 0
means top-left graph

This sets title for top-left graph. same for all of them
"""

axes[0,1].set_title("Distribution of Second Column")#sets title for second graph
axes[0,1].hist(df["col2"]); #creates histogram for column2

axes[1,0].set_title("Distribution of Third Column")#sets title for third graph
axes[1,0].hist(df["col3"]); #creates histogram for column3

axes[1,1].set_title("Distribution of Fourth Column")#sets title for fourth graph
axes[1,1].hist(df["col4"]); #creates histogram for column4

data_to_plot = [df["col1"],df["col2"],df["col3"],df["col4"]] #stores all numeric columns into list ,this is the datalist for Boxplot 

sns.set_style("whitegrid")# setting the plot style in which we applies white grid background style
# Creating a figure instance
fig = plt.figure(1, figsize=(12,8))# it will creates the plotting figure for graph

# Creating an axes instance  axes means actual plotting area
ax = fig.add_subplot(111) #here we are creating  axes instance for the figure created above, 111 means 1 row, 1 column and 1st plot/position which is located at one of the corners of the figure container

# Creating the boxplotA boxplot (or box-and-whisker plot) is a graph used to show the spread of data and detect outliers.
bp = ax.boxplot(data_to_plot) 
"""
A boxplot (or box-and-whisker plot) is a graph used to show the spread of data and detect outliers.
Why Boxplot is Useful

It helps to:

Compare distributions
Find outliers
Understand spread of data
Compare categories
"""

"""Create a boxplot for each feature in the dataset. All of the boxplots should be combined into a single plot. Compare distributions and identify outliers.



If we observe closely. for the box 2, interquartile distance is roughly around 0.75 hence the values lying beyond this range of (third quartile + interquartile distance) i.e. roughly around 4.05 will be considered as outliers. Similarly outliers with other boxplots can be found
"""

sns.boxplot(x='col1', y='col2', data=df)
"""
Meaning
sns.boxplot() → creates a boxplot
x='col1' → values/categories on X-axis
y='col2' → numerical data on Y-axis
data=df → dataframe used
Example

Suppose:

x='Gender'
y='Salary'

Then the boxplot compares salary distribution for each gender.
"""

sns.boxplot(x='col3', y='col4', data=df)