# -*- coding: utf-8 -*-
"""1Data_Wrangling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/190PrR97w0lZjNd93OebQJGF3HJrxJ4gx
"""

import pandas as pd

import numpy as np

df = pd.read_csv("data1.csv")
df

df.dtypes

df.info

df.describe()

df.notnull()

df.shape

df.size

df.index

df.head()

df.tail()

df.tail(n=5)

df.columns

df.columns.values

df.index

df.sort_index(axis=1,ascending=True)

df.iloc[4]

df[1:5]

df.iloc[:5,0:1]

df.iloc[:8,:2]

df.iloc[:,3]

df.iloc[3:5,0:2]

df.iloc[1,1]

df['Sepal Length']

df['Sepal Length'].iloc[9]

cols_2_4=df.columns[2:4]
df[cols_2_4]

df[df.columns[2:4]].iloc[5:10]

df

from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
x=df.iloc[0:150,0:4]
x

x_scaled = min_max_scaler.fit_transform(x)
x_scaled

df_normalized = pd.DataFrame(x_scaled)

df_normalized

df['Species'].unique()

df

label_encoder = preprocessing.LabelEncoder()
df['species'] = label_encoder.fit_transform(df['Species'])
df['species']

features_df = df.drop(columns=['Species'])
features_df

enc = preprocessing.OneHotEncoder()
enc_df=pd.DataFrame(enc.fit_transform(df[['Species']]).toarray())

df_encode = features_df.join(enc_df)
df_encode

df_encode.rename(columns = {0:'Iris-Setosa',1:'Iris-Versicolor',2:'Iris-virginica'}, inplace = True)
df_encode