# -*- coding: utf-8 -*-
"""2Data_Wrangling2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wtk6fb9vCDTUAppRv_KrA-NGB-RREW3Y
"""

import pandas as pd
import numpy as np

df=pd.read_csv("data2.csv") 

df

df.isnull() #Check Missing Values checks every cell and True → missing value , False → value exists

series = pd.isnull(df["math score"])
df[series]

df.notnull()# Check Non-Missing Values True → value present, False → missing

series1 = pd.notnull(df["math score"]) #Checks rows where math score exists.
df[series1] #Displays rows where math score exists.

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() #object to perform label encoding
df['gender'] = le.fit_transform(df['gender']) #Encoding the gender column as gender->male,female becomes 1,0 respectively
newdf=df
df

df

missing_values = ["Na", "na"," "]
df = pd.read_csv("data2.csv", na_values = missing_values) # Sometimes missing values are stored as: "Na" "na" blank space We tell pandas to treat them as NaN. after when we reload dataset this missing values becomes NaN
df

ndf=df
ndf.fillna(0) #replace all NaN values to 0
ndf

df['reading score'] = df['reading score'].fillna(df['reading score'].median()) # replacing the missing values in reading score column with median of that column
df

df['math score'] = df['math score'].fillna(df['math score'].mean()) # replacing the missing values in math score column with mean of that column
df

df['writing score'] = df['writing score'].fillna(df['writing score'].std()) # replacing the missing values in writing score column with standard deviation of that column 
df

df['Placement Score'] = df['Placement Score'].fillna(df['Placement Score'].min()) # replacing the missing values in placement score column with minimum value of that column
df

df

ndf.replace(to_replace = np.nan, value = -99) #All missing values NaN become: -99 Useful when model/system requires numeric placeholder.

ndf.dropna() # Deletes rows containing any NaN.. By default, it operates on rows (axis=0).

ndf.dropna(how = 'all') #Deletes rows only if: ALL columns are NaN.

ndf.dropna(axis = 1) #operate on columns .Deletes columns having missing values.

new_data = ndf.dropna(axis = 0, how ='any') #axis=0 means operate on rows, how="any" means Deletes rows if even one value is missing.
new_data #clean dataset 

df=pd.read_csv("data22.csv")
df

print(np.where(df['math score']>90)) #Returns the index of rows where math score is greater than 90. np.where() is a function that returns the indices of elements in an array that satisfy a given condition.
print(np.where(df['reading score']<25)) #Returns the index of rows where reading score is less than 25.
print(np.where(df['writing score']<30)) #Returns the index of rows where writing score is less than 30.

from scipy import stats # importing statistics library to find z score

z = np.abs(stats.zscore(df['math score'])) # calculates the Z score with zcore() function and .abs() function is used to get/convert -ve z score to +ve because we are interested in the magnitude of z score not the direction. It is calculated as: Z = (X - μ) / σ where X is the value, μ is the mean, and σ is the standard deviation of the dataset.

print(z)

threshold = 0.18 #threshold decides which values are considered outliers usually z>3 are outliers here threshold is very small

sample_outliers = np.where(z <threshold) # get indexes where z-score is less than threshold
sample_outliers

sorted_rscore= sorted(df['reading score']) # sorts the values in ascending order
sorted_rscore

q1 = np.percentile(sorted_rscore, 25) #25% data lies below this value. means suppose we have 20, 25, 30, 35, 40, 45, 50, 55, 100 and 30 is the value from it 25% data belongs

q3 = np.percentile(sorted_rscore, 75) #75% data lies below this value. means suppose we have 20, 25, 30, 35, 40, 45, 50, 55, 100 and 50 is the value from it 75% data belongs
print(q1,q3)

IQR = q3-q1 # Inter Quartile Range It tells: spread of middle 50% data

lwr_bound = q1-(1.5*IQR) #lower bound calculation we calculate it from above data as- 30 - 1.5(20)=0 lower bound=0 it means any value below 0 is outlier
upr_bound = q3+(1.5*IQR) ##upper bound calculation we calculate it from above data as-  50 + 1.5(20)=80 upper bound=80 it means any value above 80 is outlier
print(lwr_bound, upr_bound) # prints 0 80

r_outliers = [] # empty array to store the outliers
for i in sorted_rscore:  # loop which checks every score one by one
  if (i<lwr_bound or i>upr_bound): # If value: less than lower bound OR greater than upper bound , then it is outlier.
    r_outliers.append(i) # store the outlier into the list
  print(r_outliers) # prints the list