# -*- coding: utf-8 -*-
"""3Central_Tendency.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PIvICSwTw6hWmdTrQNt_0emAlbIrcrPK
"""

import pandas as pd # pandas library is to handle/perform the dataframe operation and statistical calculation
import numpy as np # numpy is used to numerical operation 

df = pd.read_csv("data3.csv")
df

df.info() #Shows: total rows, total columns, datatype, null values

df.describe() #Calculates statistics for numeric columns: count, mean, std, min , max, quartiles

from sklearn import preprocessing #importing the preprocessing module
enc = preprocessing.OneHotEncoder() # here we  creates the object of oneHotEncoding to use their methods/function 
enc_df = pd.DataFrame(enc.fit_transform(df[['Genre']]).toarray())  # here we are selecting Genre column , fit_transform learns categories and convert it into binary from(normalize it) it gives us sparse matrix and 
#toarray() convert that sparse matrix into array , Dataframe(). create an dataframe and convert that array into dataframe
enc_df

df1 = df.join(enc_df) #combines orginal dataframe and encoded dataframe

df1

del df1['Genre'] #delets original genre column , removes the text column because encoded columns already exists
 
df1 # now dataset contains only numeric values

df1.mean() # Calculates mean of every numeric column.(all columns)

df1.mean(axis=0)        #axis=0 operate column-wise. Calculates average(means) of each column.

df1.mean(axis=1)        # axis=1 operate row-wise.Calculates average of values in each row.

df1.mean(axis=1)[0:4]   # To find mean row wise calculate First 4 Row Means

df1.loc[:,'Age'].mean()  #To find mean of specific column , loc=label based selection, : =means all rows 

df1.median() #Median = middle value after sorting. ex. 10,20,30,40,50 - median=30

df1.mode() #Most frequently occurring value.ex. 10,20,20,50 - mode=20

df1.std() # calculates the standared deviation of data

df1.min() #Finds smallest value in each column

df1.max() #Finds largest value in each column.

df.groupby(['Genre'])['Age'].mean() # first groups a data according to genre it has two genre as- male, female that means two groups are created, then select age column and Find average Age for each Genre.

df.groupby(['Genre'])['Annual Income'].max() #Group data by Genre - Select Annual Income- Find maximum income in each group