# -*- coding: utf-8 -*-
"""4Linear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fvqOCChdr7NqdsVq_MdR7W0S0a-W4W9S

# Simple Linear Regression
"""

"""
Simple Linear Regression
Goal:
Predict one value using another value.
Example:
Predict house area using house price

What is Linear Regression?

Linear Regression finds relationship between:

Independent Variable (X)
Dependent Variable (y)

It tries to fit a straight line.
equation-> y=mx+ b
where y = predicted value
m = slope/coefficient
x = input
b = intercept
"""

import numpy as np # mathematical calculations , sqaure roots, arrays
import pandas as pd # reading csv, dataframe handling
from sklearn.linear_model import LinearRegression # Imports Linear Regression model from Scikit-learn. Used to train regression model.
from sklearn.model_selection import train_test_split # Imports function to split dataset into: training data ,testing data
from sklearn.metrics import mean_squared_error, r2_score  # Imports evaluation metrics. Used to check model accuracy.

# Load Boston housing dataset
data = pd.read_csv('data4.csv')
X = data.iloc[:, 0].values.reshape(-1, 1)  # iloc selects all rows and first column, .values it converts dataframe column into numpy array, .reshape(-1,1)- converts 1D array into 2D array Why reshape needed? Scikit-learn expects: 2D input
y = data.iloc[:, 1].values # selects the all rows of second column , this is the target / output variable

X #shows the input feature values

y # shows the output values

"""
# Split data into training and testing sets
 
 Why split data?

We train model on one part and test on another part.

This checks whether model predicts correctly on unseen data.
"""
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2) # test_size=2 means 20% data is for testing and 80% data is for training . random_state=2 means Fixes random splitting. So every run gives same split.

# Create a Linear Regression model
model = LinearRegression() # creates an empty linear regression model
model.fit(x_train, y_train) # this will trains the model and What happens? Model learns: relationship between X and y ,best-fit line & It calculates: slope/coefficient, intercept

# Make predictions
y_pred = model.predict(x_test) #Uses trained model to predict outputs for testing data.

# Model Evaluation Metrics
mse = mean_squared_error(y_test, y_pred) # mean  squared error
"""
What is MSE?

Measures prediction error.

Formula:

MSE=1/n∑(yi−yi^)2

Where:

actual value − predicted value
square the error
average it
Meaning

Smaller MSE:

better model
"""
rmse = np.sqrt(mse) #Root Mean Squared Error
"""
RMSE=squarerrot of MSE
 Why RMSE?

Brings error back to original unit.

Smaller RMSE = better predictions.
""" 
r2 = r2_score(y_test, y_pred)
"""
R² Score
Measures how well model fits data.

Formula:

R^2=1−SStot/SSres
Range of R²
Value	Meaning
1	Perfect prediction
0	Poor model

Closer to 1 is better.
"""

# Print model parameters
print(f'Intercept: {model.intercept_}') #prints intercept b
print(f'Coefficient: {model.coef_[0]}') #prints slope m
print(f'Mean Squared Error: {mse}') #Shows average(mean) squared prediction error.
print(f'Root Mean Squared Error (RMSE): {rmse}') #Shows square root of error. means mse
print(f'R-Squared Score (R²): {r2}') #Shows model accuracy.

# User input for price and predicting area
user_price = float(input("Enter the house price : ")) #user enters the price as input 
predicted_area = (model.intercept_ + model.coef_[0] * user_price)  #It uses the learned regression equation: y^=b+mx
'''
1. model.intercept_

This is:

Intercept (b)

It is the point where line cuts Y-axis.

Example:

b = 10

Meaning:
when x = 0,
prediction starts from 10.

2. model.coef_[0]

This is:

Slope / Coefficient (m)

It tells:

how much y changes when x increases by 1.

Example:

m = 2

Meaning:
if price increases by 1,
area increases by 2.

3. user_price

This is the input value entered by user.
'''
print(f'Predicted area : {predicted_area}') # displays the final predicted value