# -*- coding: utf-8 -*-
"""5Logistic_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yRdsXn0zijCM1qYsGHgro6ZtmjK4mmi2

    This program performs:

Logistic Regression Classification

Used for predicting categories like:

Yes/No
0/1
Buy/Not Buy
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression #Imports Logistic Regression model.
from sklearn.metrics import confusion_matrix

# Load dataset
df = pd.read_csv('data5.csv')

# Drop 'Gender' column
df1 = df.drop("Genre", axis=1) #removes the 'Genre' column from the dataset. axis=1 means we are dropping a column (axis=0 would mean dropping a row).

# Define features and target variable
y = df1.iloc[:, -1].values  # Target variable Selects last column as output/target variable.
X = df1.iloc[:, :-1].values  # Feature set

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=2) #Splits dataset into training and testing sets. test_size=0.25 means 25% data for testing, 75% for training. random_state=2 ensures same split every time.

# Train Logistic Regression model
LR = LogisticRegression() #Creates Logistic Regression model object. 
LR.fit(X_train, y_train) #Trains model using training data. Learns relationship between features and target variable.

# Compute confusion matrix
y_pred = LR.predict(X_test) #Predicts outputs for testing data.
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()  #.ravel() converts the 2x2 matrix into a 1D array.
"""
Creates confusion matrix and converts it into 4 values.

Confusion Matrix Structure
Actual / Predicted	Positive	Negative
Positive	TP	FN
Negative	FP	TN

Meaning
Term	Meaning
TP	correctly predicted positive
TN	correctly predicted negative
FP	wrong positive prediction
FN	wrong negative prediction
"""


# Calculate metrics
accuracy = (tn + tp) * 100 / (tp + tn + fp + fn)
precision = tp / (tp + fp)
recall = tp / (tp + fn)
f1_score = (2 * precision * recall) / (precision + recall)
specificity = tn / (tn + fp)

# Display metrics
print(f"Accuracy: {accuracy:.2f}%") #Means:show 2 digits after decimal Example:95.4567 → 95.46
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1_score:.2f}")
print(f"Specificity: {specificity:.2f}")

# Take user input for feature values
print("Enter values for the following features (Cust_ID, Age, Income):")
input_features = [] #empty list to store user input values
for i in range(3): # loop runs 3 times for 3 features: Cust_ID, Age, Income
    val = float(input(f"Feature {i+1}: "))  #User enters numeric values. f-strings are used to format the input prompt. {i+1} will display the feature number (1, 2, 3).
    input_features.append(val) #Adds value to list.

# Convert input into numpy array and reshape
input_array = np.array(input_features).reshape(1, -1)  #reshaped into a 2D array (1 row and multiple col) because scikit-learn expects 2D input.

# Make prediction
prediction = LR.predict(input_array)[0] #Predicts output for user input.  Extracts first prediction value.
print(f"Predicted Output: {prediction}") #Prints final predicted class.