# -*- coding: utf-8 -*-
"""6Naïve_Bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11pfGoY1qlcjY_8aM1ahFtxFKd7gPjKwu

# Naive Bayes

## Importing the libraries
"""

import numpy as np
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('data6.csv')
dataset

X = dataset.iloc[:, :-1].values #selects all rows and all columns except the last column, this is the input feature set
y = dataset.iloc[:, -1].values #selects all rows and only the last column, this is the target variable

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 2)

"""
Splits dataset:

75% → training data
25% → testing data
Variables
X_train → training input
X_test → testing input
y_train → training output
y_test → testing output
Parameters
test_size=0.25
25% data for testing
random_state=2
keeps same random split every time
"""
"""## Training the Naive Bayes model on the Training set"""

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB() #Creates Naive Bayes model object.
classifier.fit(X_train, y_train) #Trains model using training data. Learns relationship between inputs and outputs.

"""## Predicting the Test set results"""

y_pred = classifier.predict(X_test) #Predicts outputs for testing data.
y_pred #display the predicted values

# Evaluate the performance of Model for train_y and
from sklearn.metrics import precision_score,confusion_matrix,accuracy_score,recall_score # Imports evaluation metrics and functions. Used to check model accuracy.
accuracy = accuracy_score(y_test,y_pred)
"""Measures how many predictions are correct.
Formula:
Accuracy=Correct Predictions/Total Predictions
"""
precision =precision_score(y_test, y_pred,average='micro') #Measures how many positive predictions are actually correct.
recall = recall_score(y_test, y_pred,average='micro') #Measures how many actual positives are correctly identified.
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}") #above 3 lines displays the evaluation stores

"""## Making the Confusion Matrix"""
"""
confusion_matrix() is a function from scikit-learn used to compare:
Actual values
Predicted values
It shows:
Correct predictions
Wrong predictions
"""

from sklearn.metrics import confusion_matrix #Imports confusion matrix function.
cm = confusion_matrix(y_test, y_pred) #Creates confusion matrix. y_test contains the actual correct answers from testing dataset.y_pred contains values predicted by the model.
# Display the confusion matrix and evaluation metrics
print("Confusion Matrix:")
print(cm)

# Accept user input for prediction
age = float(input("Enter age: "))
salary = float(input("Enter salary: "))

# Reshape the input to a 2D array
input_data = [[age, salary]] #

# Make the prediction
prediction = classifier.predict(input_data)

print(f"The predicted class for age {age} and salary {salary} is: {prediction[0]}")