# -*- coding: utf-8 -*-
"""7Term Frequency.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pvt_yHUtTgHnDG429KDz5EP2E3qR_STl
"""

"""
This program performs basic:
Natural Language Processing (NLP)
and finally calculates:
Term Frequency (TF)
TF-IDF
using two text documents.

What is NLP?
NLP means:
Natural Language Processing
It helps computers understand human language.
Example:
ChatGPT
Google Translate

What is NLTK?
NLTK = Natural Language Toolkit

Used for:
tokenization
stemming
stopword removal
POS tagging

What are Stopwords?
Common words like:
is
am
the
of
Usually removed because they carry less meaning.

POS Tagging
POS =Part Of Speech
Identifies:
noun
verb
adjective

Stemming
Stemming means reducing a word to its root/base form by removing prefixes or suffixes.
Example:
playing → play
played → play
studies → studi
Here, the stemmer simply cuts letters from the end of words.
Important Point
Sometimes the final word is not a real English word.

Lemmatization
Lemmatization also converts words to base form, but it uses dictionary meaning and grammar rules.

Example:
playing → play
studies → study
better → good

The result is usually a valid English word.
Important Point
Lemmatization is smarter but slower than stemming.

It checks:
Meaning
Context
Part of speech

What is CountVectorizer?
Counts how many times each word appears.
This is called:
Term Frequency (TF)

What is TF-IDF?
TF-IDF means:
Term Frequency × Inverse Document Frequency
It gives importance score to words.

Idea
Words appearing:
many times in one document
BUT
not common in all documents
get higher importance.

Formula
TF-IDF=TF×log(N/DF)
Where:
TF = term frequency
N = total documents
DF = documents containing word
Example
Word:
Artificial
appears in both docs → less unique → lower score.
Word:
fascinating
appears in only one doc → higher importance.
"""

# ----------------------------------------------------------
# STEP 1: Import Libraries
# ----------------------------------------------------------
import nltk
from nltk.tokenize import word_tokenize #importing tokenizer used to split the sentence into words
from nltk.corpus import stopwords #importing stopword which removes words that does not have large/important meaning like is, am etc
from nltk.stem import PorterStemmer, WordNetLemmatizer #import stemming and lemmatiazation tools
from nltk import pos_tag #importing POS tagging part-of-speech
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer #countVectorizer - for term Frequency, TfidfVectorizer- for TF-IDF calculations

# Download (first time only)
nltk.download('punkt') #Downloads tokenizer data.
nltk.download('stopwords') #Downloads stopwords dataset.
nltk.download('averaged_perceptron_tagger') #Downloads POS tagger model.
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('wordnet') #Downloads WordNet for lemmatization.
nltk.download('punkt_tab')

# ----------------------------------------------------------
# STEP 2: Sample Documents (2 documents)
# ----------------------------------------------------------
documents = [
    "Natural Language Processing is a fascinating field of Artificial Intelligence.",
    "Artificial Intelligence helps computers understand human language."
] #Creates list containing 2 documents.

print("\nOriginal Documents:")
for i, doc in enumerate(documents, 1): #enumerate keywords is used to give both item number and item value while looping
    print(f"Doc {i}: {doc}") #loop to print orginal document 

# ----------------------------------------------------------
# STEP 3: Tokenization
# ----------------------------------------------------------
print("\nTokenization:")
all_tokens = [] #create an empty list to store tokens
for i, doc in enumerate(documents, 1): #loop through documents
    tokens = word_tokenize(doc) #splits the sentence into words/tokens
    all_tokens.append(tokens) #Stores tokens into list.
    print(f"Doc {i} Tokens:", tokens) #it will display tokens

# ----------------------------------------------------------
# STEP 4: POS Tagging
# ----------------------------------------------------------
print("\nPOS Tagging:")
for i, tokens in enumerate(all_tokens, 1): #loop through tokenized document
    pos_tags = pos_tag(tokens) #Assigns grammatical labels. ex ("dog","NN"), dog=noun, vb-verb, jj-adjective 
    print(f"Doc {i} POS Tags:", pos_tags) #Displays tagged words.

# ----------------------------------------------------------
# STEP 5: Stop Words Removal
# ----------------------------------------------------------
stop_words = set(stopwords.words('english')) #Loads the english stopwords
filtered_docs = [] # empty list for filtered words

print("\nAfter Stop Words Removal:")  
for i, tokens in enumerate(all_tokens, 1): # loop through tokenized document 
    filtered = [word for word in tokens if word.lower() not in stop_words] # this is the list of comprehension means keeps only meaningful words
    filtered_docs.append(filtered) #Stores cleaned words.
    print(f"Doc {i}:", filtered) #displays the clean tokens

# ----------------------------------------------------------
# STEP 6: Stemming
# ----------------------------------------------------------
ps = PorterStemmer() #creates the stemming object
print("\nStemming:")
for i, tokens in enumerate(filtered_docs, 1): #loop through filtered_docs
    stemmed = [ps.stem(word) for word in tokens] #Applies stemming to every word.
    print(f"Doc {i}:", stemmed) #Displays stemmed words.

# ----------------------------------------------------------
# STEP 7: Lemmatization
# ----------------------------------------------------------
lemmatizer = WordNetLemmatizer() #Creates lemmatizer object.
print("\nLemmatization:")
for i, tokens in enumerate(filtered_docs, 1): #loop through filtered_docs
    lemmatized = [lemmatizer.lemmatize(word) for word in tokens] #Applies lemmatization.
    print(f"Doc {i}:", lemmatized) #Displays lemmatized words.

# ----------------------------------------------------------
# STEP 8: Term Frequency (CountVectorizer)
# ----------------------------------------------------------
cv = CountVectorizer() #Creates CountVectorizer object.
tf_matrix = cv.fit_transform(documents) # fit()-learns vocabulary words, trasform()- creates the frequency matrix

print("\nTerm Frequency (CountVectorizer):")
print("Feature Names:", cv.get_feature_names_out()) #Returns all unique words/features.
print("TF Matrix:\n", tf_matrix.toarray()) #Converts sparse matrix into normal array.

# ----------------------------------------------------------
# STEP 9: TF-IDF Representation
# ----------------------------------------------------------
tfidf = TfidfVectorizer() #Creates TF-IDF object.
tfidf_matrix = tfidf.fit_transform(documents) #Creates TF-IDF matrix.

print("\nTF-IDF Representation:")
print("Feature Names:", tfidf.get_feature_names_out()) #Shows vocabulary words.
print("TF-IDF Matrix:\n", tfidf_matrix.toarray()) #Displays TF-IDF scores.