# -*- coding: utf-8 -*-
"""8Data Visualization1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XX8dlvmPc8YZwemP1wYFKs13xwDzYNoz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dataset=pd.read_csv('data8.csv')
dataset

sns.distplot(dataset['Fare'])

"""The Dist Plot
The distplot() shows the histogram distribution of data for a single column. The column name is passed as a parameter to the distplot() function. Let's see how the price of the ticket for each passenger is distributed.
"""

sns.distplot(dataset['Fare'], kde=False)

"""kde(Guassian kernal Density Estimate):
Now you can see there is no line for the kernel density estimation on the plot.

You can also pass the value for the bins parameter in order to see more or less details in the graph. Take a look at he following script:
"""

sns.distplot(dataset['Fare'], kde=False, bins=10)

"""Bins (Height of the bar plot which means how many datapoint are threr in that particular bin)"""

sns.jointplot(x='Age', y='Fare', data=dataset)

"""The Joint Plot
The jointplot()is used to display the mutual distribution of each column. You need to pass three parameters to jointplot. The first parameter is the column name for which you want to display the distribution of data on x-axis. The second parameter is the column name for which you want to display the distribution of data on y-axis. Finally, the third parameter is the name of the data frame.
"""

sns.pairplot(dataset)

"""The paitplot() is a type of distribution plot that basically plots a joint plot for all the possible combination of numeric and Boolean columns in your dataset. You only need to pass the name of your dataset as the parameter to the pairplot() function as shown below:"""

sns.rugplot(dataset['Fare'])

"""he rugplot() is used to draw small bars along x-axis for each point in the dataset. To plot a rug plot, you need to pass the name of the column. Let's plot a rug plot for fare.From the output, you can see that as was the case with the distplot(), most of the instances for the fares have values between 0 and 100."""

sns.barplot(x='Sex', y='Age', data=dataset)

"""The barplot() is used to display the mean value for each value in a categorical column, against a numeric column. The first parameter is the categorical column, the second parameter is the numeric column while the third parameter is the dataset. For instance, if you want to know the mean value of the age of the male and female passengers,"""

sns.countplot(x='Fare', data=dataset)

sns.boxplot(x='Sex', y='Age', data=dataset)

sns.boxplot(x='Survived', y='Fare', data=dataset)

sns.boxplot(x='Sex', y='Age', data=dataset, hue="Survived")

"""Now in addition to the information about the age of each gender, you can also see the distribution of the passengers who survived. For instance, you can see that among the male passengers, on average more younger people survived as compared to the older ones. Similarly, you can see that the variation among the age of female passengers who did not survive is much greater than the age of the surviving female passengers."""

sns.violinplot(x='Sex', y='Age', data=dataset, hue='Survived')

""" The violinplot() function is used to plot the violin plot. Like the box plot, the first parameter is the categorical column, the second parameter is the numeric column while the third parameter is the dataset. if you look at the bottom of the violin plot for the males who survived (left-orange), you can see that it is thicker than the bottom of the violin plot for the males who didn't survive (left-blue). This means that the number of young male passengers who survived is greater than the number of young male passengers who did not survive. The violin plots convey a lot of information, however, on the downside, it takes a bit of time and effort to understand the violin plots."""

sns.stripplot(x='Sex', y='Age', data=dataset)

"""The stripplot() function is used to plot the violin plot. Like the box plot, the first parameter is the categorical column, the second parameter is the numeric column while the third parameter is the dataset."""

sns.histplot(data=dataset,x='Fare',y='Survived')